### ISSUE TITLE
plonk_Saw.h:357:28: No type named 'CurrentValueType' in 'SawProcessStateF'

### ISSUE THREAD

**Issue by jamiebullock** [0x4d52/pl-nk#5]
I'm getting the above compiler error when trying to compile the following minimal code:

> Unit u = Saw::ar(440.0);

What's less clear to me is why `SawChannelInternal` isn't using one of th `PLONK_CHANNELDATA_SPECIAL` structs, which do indeed declare a `CurrentValueType` type

**Comment by 0x4d52** [comment]
Using macplnk
