### ISSUE TITLE
getTime() for a SignalPlay unit...?

### ISSUE THREAD

**Issue by jamiebullock** [0x4d52/pl-nk#6]
I'm not sure if I'm using the correct terminology here, but it seems like SignalPlay is a wrapper around n channels of buffers, where the corresponding `Unit` returned by `ar()` has the ability to automatically "play" the buffers (through the `process()` call) taking account of various bits of state such as looping and play position. As such, it would be very useful to obtain the current play position from a running unit. 

So is there any way to get the current position of a `SignalPlay` with Plonk as it stands? If not, does this seem a sensible feature request?

Note: I'm aware I can effectively do a `getTime()` if I use `SignalRead` driven by a `Saw` by calling `getValue()` on the `Saw` unit, however `SignalPlay` is a bit more convenient with the looping support

**Comment by 0x4d52** [comment]
Typical use would be to to do the latter and use SignalRead driving its position with a value that you hold. This is the idiom of the API in that you would not generally inspect a Unit for its state but you would have passed it a shared value that you can hold onto and inspect at a later time.
